[[redirects]]
  from = "https://yawudb.com"
  to = "https://wunderworlds.club"
  force = true
  status = 301

[[redirects]]
  from = "/__/auth/*" 
  to = "https://yawudb.firebaseapp.com/__/auth/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"

  [headers.values]
    # Multi-value headers are expressed with multi-line strings.
    cache-control = '''public, max-age=5256000''' 

[[headers]]
  for = "index.html"

  [headers.values]
    cache-control = '''
    no-store'''
