// Values are kebab-case fighter slugs that match the asset filename suffix
// `/assets/fighters/${faction}/${faction}-${slug}.png`. For warbands not yet
// migrated to slug-based assets, values remain placeholders matching the
// numeric file suffix (`-1.png`, `-2.png`, ...).

export const factionMembers = {
  universal: [],
  "grand-aliance-order": [],
  "grand-aliance-chaos": [],
  "grand-aliance-death": [],
  "grand-aliance-destruction": [],
  "garreks-reavers": ["Garrek", "Saek", "Karsus", "Targor", "Arnulf"],
  "steelhearts-champions": ["Steelheart", "Obryn", "Angharad"],
  "sepulchral-guard": [
    "the-sepulchral-warden",
    "the-champion",
    "the-prince-of-dust",
    "the-harvester-petitioner",
    "the-inevitable-petitioner",
    "the-rising-petitioner",
    "the-zealous-petitioner",
  ],
  "ironskulls-boyz": ["Gurzag", "Bonekutta", "Hakka", "Basha"],
  "the-chosen-axes": ["Grimnir", "Tefk", "Vol", "Maegrim"],
  "spiteclaws-swarm": [
    "spiteclaw",
    "krrk",
    "lurking-skaven",
    "festering-skaven",
    "hungering-skaven",
  ],
  "magores-fiends": ["Magore", "Riptooth", "Zharkus", "Ghartok"],
  "the-farstriders": ["farstrider", "swiftblade", "eagle-eye"],

  // NIGHTVAULT

  "stormsires-cursebreakers": ["Stormsire", "Ammis", "Rastus"],
  "thorns-of-the-briar-queen": [
    "the-briar-queen",
    "varclav",
    "the-ever-hanged",
    "the-ironwretch",
    "the-exhumed",
    "the-uncrowned",
  ],
  "eyes-of-the-nine": [
    "Vortemis",
    "K'charik",
    "Narvia",
    "Turosh",
    "Blue Horror",
  ],
  "zarbags-gitz": [
    "zarbag",
    "snirk",
    "drizgit",
    "bonekrakka",
    "gobbaluk",
    "prog",
    "stikkit",
    "redkap",
    "dibbz",
  ],
  "godsworn-hunt": [
    "Theddra",
    "Grundann",
    "Jagathra",
    "Shond",
    "Ollo",
    "Grawl",
  ],
  "mollogs-mob": ["mollog", "bat-squig", "stalasquig", "spiteshroom"],
  "thundriks-profiteers": ["thundrik", "lund", "enrik", "khazgan", "garodd"],
  "yltharis-guardians": ["ylthari", "ahnslaine", "gallanghann", "skhathael"],

  // DREADFANE

  "ironsouls-condemners": ["ironsoul", "brodus", "tavian"],
  "lady-harrows-mournflight": [
    "Lady Harrow",
    "The Anguished One",
    "The Maiden",
    "Widow Caitha",
  ],

  // BEASTGRAVE

  "grashraks-despoilers": [
    "Grashrak",
    "Draknar",
    "Murgroth",
    "Korsh",
    "Gnarl",
    "Ushkor",
  ],
  "skaeths-wild-hunt": [
    "Skaeths",
    "Lighaen",
    "Karthaen",
    "Kurnoth4",
    "Kurnoth5",
  ],
  "the-grymwatch": [
    "master-talon",
    "nights-herald",
    "crackmarrow",
    "gristlewel",
    "valreek",
    "the-royal-butcher",
    "the-dukes-harriers",
  ],
  "rippas-snarlfangs": ["Rippa", "Stabbit", "Mean-Eye"],
  "hrothgorns-mantrappers": [
    "Hrothgorn",
    "Thrafnir",
    "Bushwakka",
    "Quiv",
    "Luggit and Thwak",
  ],
  "the-wurmspat": ["Fecula", "Ghulgogh", "Sepsimus"],
  "morgwaeths-blade-coven": [
    "Morgwaeth",
    "Kyrae",
    "Khamyss",
    "Kyrssa",
    "Lethyr",
  ],

  "morgoks-krushas": ["morgok", "ardskull", "thugg"],

  // DIRECHASM
  "myaris-purifiers": ["myari", "bahannar", "ailenn", "senaela"],
  "the-dread-pageant": ["vasiliac", "glissete", "hadzu", "slakeslash"],
  "khagras-ravagers": ["khagra", "cragan", "razek", "zarshia"],
  "the-starblood-stalkers": [
    "Kixi-Taka",
    "Klaq-Trok",
    "Otapatl",
    "Tok",
    "Xepic",
    "Huachi",
  ],
  "the-crimson-court": ["duvalle", "ennias", "gorath", "vellas"],
  "storm-of-celestus": ["1", "2", "3", "4"],
  "drepurs-wraithcreepers": ["1", "2", "3", "4"],
  "hedkrakkas-madmob": ["Hedkrakka", "Wollop", "Toofdagga", "Dakko"],
  "kainans-reapers": ["kainan", "hakor", "karu", "khenta", "nohem", "senha"],
  "elathains-soulraid": ["1", "2", "3", "4", "5"],

  "xandires-truthseekers": ["1", "2", "3", "4"],
  "da-kunnin-krew": ["torka", "krookgrin", "shank", "mannok", "gikkit"],
  "blackpowders-buccaneers": ["Gorlok", "Kagey", "Mange", "Peggs", "Shreek"],
  "the-exiled-dead": [
    "Deintalos",
    "Marcov",
    "Regulus",
    "Coyl",
    "Bault",
    "Vlash",
    "Ione",
  ],
  "skittershanks-clawpack": [
    "Skittershanks",
    "Snyp",
    "Kreep",
    "Krowcht",
    "Skulck",
  ],
  "the-shadeborn": ["Slythael", "Drusylla", "Sylarc", "Valyssa"],
  "hexbanes-hunters": [
    "haskel",
    "aemos",
    "pock",
    "brydget",
    "grotbiter",
    "ratspike",
  ],
  "gorechosen-of-dromm": ["dromm", "gorehulk", "herax"],
  "gnarlspirit-pack": ["1", "2", "3", "4"],
  "sons-of-velmorn": ["1", "2", "3", "4", "5"],
  "grinkraks-looncourt": [
    "grinkrak",
    "snorbo",
    "nagz",
    "burk",
    "snark",
    "grib",
    "sholko-and-pronk",
  ],
  "gryselles-arenai": ["1", "2", "3", "4", "5"],
  "domitans-stormcoven": ["1", "2", "3"],
  "ephilims-pandaemonium": [
    "ephilim",
    "kindlefinger",
    "spawnmaw",
    "flamespooler",
    "apotrax",
  ],
  "the-headsmens-curse": [
    "wielder-of-the-blade",
    "scriptor-of-the-sentence",
    "sharpener-of-the-blade",
    "bearer-of-the-block",
  ],
  "skabbiks-plaguepack": ["1", "2", "3", "4", "5", "6"],
  "cyrenis-razors": ["cyreni", "cephanyr", "renglaith", "alathyrr"],
  "the-thricefold-discord": ["lascivyr", "vexmor", "vashtiss"],
  "daggoks-stab-ladz": ["daggok", "hurrk", "grakk", "jagz"],
  "zondaras-gravebreakers": ["zondara", "cracktomb", "ferlain", "toyle", "pikk"],
  "brethren-of-the-bolt": ["1", "2", "3", "4", "5"],
  "the-skinnerkin": ["the-carnskyr", "kretch", "seddrik", "pewdrig", "gristla"],

  "the-emberwatch": ["1", "2", "3"],
  "zikkits-tunnelpack": ["zikkit", "krittatok", "tiktik", "rittak", "nitch"],
  "grandfathers-gardeners": [
    "phleghmus",
    "strewg",
    "slunge",
    "squort",
    "dripterus",
  ],
  "jaws-of-itzl": ["sokar", "krojax", "rotak"],
  "borgits-beastgrabbaz": ["1", "2", "3", "4", "5"],
  "knives-of-the-crone": ["azphel", "kaerna-vix", "tazari", "krieta"],
  "kamandoras-blades": ["1", "2", "3", "4", "5"],
  "kurnoths-heralds": ["1", "2", "3"],
  "blood-of-the-bull": ["1", "2", "3", "4", "5"],
  "thanateks-tithe": ["1", "2", "3", "4", "5"],
} as const;
