// Values are kebab-case fighter slugs that match the asset filename suffix
// `/assets/fighters/${faction}/${faction}-${slug}.png`. Warbands without
// proper assets keep numeric placeholders ("1", "2", ...) that match the
// legacy numeric file suffix.

export const factionMembers = {
  universal: [],
  "grand-aliance-order": [],
  "grand-aliance-chaos": [],
  "grand-aliance-death": [],
  "grand-aliance-destruction": [],
  "garreks-reavers": ["garrek", "saek", "karsus", "targor", "arnulf"],
  "steelhearts-champions": ["steelheart", "obryn", "angharad"],
  "sepulchral-guard": [
    "the-sepulchral-warden",
    "the-champion",
    "the-prince-of-dust",
    "the-harvester-petitioner",
    "the-inevitable-petitioner",
    "the-rising-petitioner",
    "the-zealous-petitioner",
  ],
  "ironskulls-boyz": ["gurzag", "bonekutta", "hakka", "basha"],
  "the-chosen-axes": ["grimnir", "tefk", "vol", "maegrim"],
  "spiteclaws-swarm": [
    "spiteclaw",
    "krrk",
    "lurking-skaven",
    "festering-skaven",
    "hungering-skaven",
  ],
  "magores-fiends": ["magore", "riptooth", "zharkus", "ghartok"],
  "the-farstriders": ["farstrider", "swiftblade", "eagle-eye"],

  // NIGHTVAULT

  "stormsires-cursebreakers": ["stormsire", "ammis", "rastus"],
  "thorns-of-the-briar-queen": [
    "the-briar-queen",
    "varclav",
    "the-ever-hanged",
    "the-ironwretch",
    "the-exhumed",
    "the-uncrowned",
  ],
  "eyes-of-the-nine": [
    "vortemis",
    "kcharik",
    "narvia",
    "turosh",
    "blue-horror",
  ],
  "zarbags-gitz": [
    "zarbag",
    "snirk",
    "drizgit",
    "bonekrakka",
    "gobbaluk",
    "prog",
    "stikkit",
    "redkap",
    "dibbz",
  ],
  "godsworn-hunt": [
    "theddra",
    "grundann",
    "jagathra",
    "shond",
    "ollo",
    "grawl",
  ],
  "mollogs-mob": ["mollog", "bat-squig", "stalasquig", "spiteshroom"],
  "thundriks-profiteers": ["thundrik", "lund", "enrik", "khazgan", "garodd"],
  "yltharis-guardians": ["ylthari", "ahnslaine", "gallanghann", "skhathael"],

  // DREADFANE

  "ironsouls-condemners": ["ironsoul", "brodus", "tavian"],
  "lady-harrows-mournflight": [
    "lady-harrow",
    "the-anguished-one",
    "the-maiden",
    "widow-caitha",
  ],

  // BEASTGRAVE

  "grashraks-despoilers": [
    "grashrak",
    "draknar",
    "murgroth",
    "korsh",
    "gnarl",
    "ushkor",
  ],
  "skaeths-wild-hunt": [
    "skaeths",
    "lighaen",
    "karthaen",
    "kurnoth4",
    "kurnoth5",
  ],
  "the-grymwatch": [
    "master-talon",
    "nights-herald",
    "crackmarrow",
    "gristlewel",
    "valreek",
    "the-royal-butcher",
    "the-dukes-harriers",
  ],
  "rippas-snarlfangs": ["rippa", "stabbit", "mean-eye"],
  "hrothgorns-mantrappers": [
    "hrothgorn",
    "thrafnir",
    "bushwakka",
    "quiv",
    "luggit-and-thwak",
  ],
  "the-wurmspat": ["fecula", "ghulgoch", "sepsimus"],
  "morgwaeths-blade-coven": [
    "morgwaeth",
    "kyrae",
    "khamyss",
    "kyrssa",
    "lethyr",
  ],

  "morgoks-krushas": ["morgok", "ardskull", "thugg"],

  // DIRECHASM
  "myaris-purifiers": ["myari", "bahannar", "ailenn", "senaela"],
  "the-dread-pageant": ["vasiliac", "glissete", "hadzu", "slakeslash"],
  "khagras-ravagers": ["khagra", "cragan", "razek", "zarshia"],
  "the-starblood-stalkers": [
    "kixi-taka",
    "klaq-trok",
    "otapatl",
    "tok",
    "xepik",
    "huachi",
  ],
  "the-crimson-court": ["duvalle", "ennias", "gorath", "vellas"],
  "storm-of-celestus": ["1", "2", "3", "4"],
  "drepurs-wraithcreepers": ["1", "2", "3", "4"],
  "hedkrakkas-madmob": ["hedkrakka", "wollop", "toofdagga", "dakko"],
  "kainans-reapers": ["kainan", "hakor", "karu", "khenta", "nohem", "senha"],
  "elathains-soulraid": [
    "elathain",
    "duinclaw",
    "fuirann",
    "spinefin",
    "tammael",
  ],

  "xandires-truthseekers": ["xandire", "dhoraz", "luxa", "taros"],
  "da-kunnin-krew": ["torka", "krookgrin", "shank", "mannok", "gikkit"],
  "blackpowders-buccaneers": ["gorlok", "kagey", "mange", "peggz", "shreek"],
  "the-exiled-dead": [
    "deintalos",
    "marcov",
    "regulus",
    "coyl",
    "bault",
    "vlash",
    "ione",
  ],
  "skittershanks-clawpack": ["snyp", "kreep", "krowcht", "skulck", "slynk"],
  "the-shadeborn": ["slythael", "drusylla", "sylarc", "valyssa"],
  "hexbanes-hunters": [
    "haskel",
    "aemos",
    "pock",
    "brydget",
    "grotbiter",
    "ratspike",
  ],
  "gorechosen-of-dromm": ["dromm", "gorehulk", "herax"],
  "gnarlspirit-pack": ["kheira", "sarrakkar", "lupan", "gorl"],
  "sons-of-velmorn": ["thain", "faulk", "helmar", "morlak", "jedran"],
  "grinkraks-looncourt": [
    "grinkrak",
    "snorbo",
    "nagz",
    "burk",
    "snark",
    "grib",
    "sholko-and-pronk",
  ],
  "gryselles-arenai": ["1", "2", "3", "4", "5"],
  "domitans-stormcoven": ["1", "2", "3"],
  "ephilims-pandaemonium": [
    "ephilim",
    "kindlefinger",
    "spawnmaw",
    "flamespooler",
    "apotrax",
  ],
  "the-headsmens-curse": [
    "wielder-of-the-blade",
    "scriptor-of-the-sentence",
    "sharpener-of-the-blade",
    "bearer-of-the-block",
  ],
  "skabbiks-plaguepack": ["1", "2", "3", "4", "5", "6"],
  "cyrenis-razors": ["cyreni", "cephanyr", "renglaith", "alathyrr"],
  "the-thricefold-discord": ["lascivyr", "vexmor", "vashtiss"],
  "daggoks-stab-ladz": ["daggok", "hurrk", "grakk", "jagz"],
  "zondaras-gravebreakers": ["zondara", "cracktomb", "ferlain", "toyle", "pikk"],
  "brethren-of-the-bolt": ["arcus", "galvic", "pater-filius", "tazat", "yakob"],
  "the-skinnerkin": ["the-carnskyr", "kretch", "seddrik", "pewdrig", "gristla"],

  "the-emberwatch": ["ardorn", "farasa", "yurik"],
  "zikkits-tunnelpack": ["zikkit", "krittatok", "tiktik", "rittak", "nitch"],
  "grandfathers-gardeners": [
    "phleghmus",
    "strewg",
    "slunge",
    "squort",
    "dripterus",
  ],
  "jaws-of-itzl": ["sokar", "krojax", "rotak"],
  "borgits-beastgrabbaz": [
    "borgit",
    "snagz",
    "dregg",
    "uglug",
    "rigg-and-shamm",
  ],
  "knives-of-the-crone": ["azphel", "kaerna-vix", "tazari", "krieta"],
  "kamandoras-blades": [
    "kamandora",
    "ghalista",
    "antro-krast",
    "kannat",
    "throkk",
  ],
  "kurnoths-heralds": ["ylarin", "lenwythe", "cullon"],
  "blood-of-the-bull": ["tokkor", "morudok", "imnidrin", "grisk", "zuldrakka"],
  "thanateks-tithe": [
    "thanatek",
    "medeb-ahk",
    "xar-tamok",
    "sekhmor",
    "tukhar",
  ],
  "thyrielles-zephyrites": ["anara", "orieth", "sikrith", "thyrielle"],
} as const;
