[[redirects]]
  from = "https://yawudb.com"
  to = "https://wunderworlds.club"
  force = true
  status = 301

[[redirects]]
  from = "/__/*"
  to = "/signin_helpers/*"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[[headers]]
  for = "/assets/*"

  [headers.values]
    # Multi-value headers are expressed with multi-line strings.
    cache-control = '''public, max-age=2628000''' 

[[headers]]
  for = "index.html"

  [headers.values]
    cache-control = '''
    no-store'''
