/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RequestPasswordResetRouteImport } from './routes/requestPasswordReset'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MydecksRouteImport } from './routes/mydecks'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as BoardsRouteImport } from './routes/boards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserSignupRouteImport } from './routes/user.signup'
import { Route as DecksFactionRouteImport } from './routes/decks.$faction'
import { Route as DeckActionRouteImport } from './routes/deck.$action'
import { Route as ViewDeckIdRouteImport } from './routes/view.deck.$id'
import { Route as ViewCardIdRouteImport } from './routes/view.card.$id'
import { Route as DeckActionDataRouteImport } from './routes/deck.$action.$data'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestPasswordResetRoute = RequestPasswordResetRouteImport.update({
  id: '/requestPasswordReset',
  path: '/requestPasswordReset',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MydecksRoute = MydecksRouteImport.update({
  id: '/mydecks',
  path: '/mydecks',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsRoute = BoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSignupRoute = UserSignupRouteImport.update({
  id: '/user/signup',
  path: '/user/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksFactionRoute = DecksFactionRouteImport.update({
  id: '/decks/$faction',
  path: '/decks/$faction',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckActionRoute = DeckActionRouteImport.update({
  id: '/deck/$action',
  path: '/deck/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewDeckIdRoute = ViewDeckIdRouteImport.update({
  id: '/view/deck/$id',
  path: '/view/deck/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewCardIdRoute = ViewCardIdRouteImport.update({
  id: '/view/card/$id',
  path: '/view/card/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckActionDataRoute = DeckActionDataRouteImport.update({
  id: '/$data',
  path: '/$data',
  getParentRoute: () => DeckActionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/mydecks': typeof MydecksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/requestPasswordReset': typeof RequestPasswordResetRoute
  '/settings': typeof SettingsRoute
  '/deck/$action': typeof DeckActionRouteWithChildren
  '/decks/$faction': typeof DecksFactionRoute
  '/user/signup': typeof UserSignupRoute
  '/deck/$action/$data': typeof DeckActionDataRoute
  '/view/card/$id': typeof ViewCardIdRoute
  '/view/deck/$id': typeof ViewDeckIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/mydecks': typeof MydecksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/requestPasswordReset': typeof RequestPasswordResetRoute
  '/settings': typeof SettingsRoute
  '/deck/$action': typeof DeckActionRouteWithChildren
  '/decks/$faction': typeof DecksFactionRoute
  '/user/signup': typeof UserSignupRoute
  '/deck/$action/$data': typeof DeckActionDataRoute
  '/view/card/$id': typeof ViewCardIdRoute
  '/view/deck/$id': typeof ViewDeckIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/mydecks': typeof MydecksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/requestPasswordReset': typeof RequestPasswordResetRoute
  '/settings': typeof SettingsRoute
  '/deck/$action': typeof DeckActionRouteWithChildren
  '/decks/$faction': typeof DecksFactionRoute
  '/user/signup': typeof UserSignupRoute
  '/deck/$action/$data': typeof DeckActionDataRoute
  '/view/card/$id': typeof ViewCardIdRoute
  '/view/deck/$id': typeof ViewDeckIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boards'
    | '/library'
    | '/login'
    | '/mydecks'
    | '/privacy-policy'
    | '/profile'
    | '/requestPasswordReset'
    | '/settings'
    | '/deck/$action'
    | '/decks/$faction'
    | '/user/signup'
    | '/deck/$action/$data'
    | '/view/card/$id'
    | '/view/deck/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boards'
    | '/library'
    | '/login'
    | '/mydecks'
    | '/privacy-policy'
    | '/profile'
    | '/requestPasswordReset'
    | '/settings'
    | '/deck/$action'
    | '/decks/$faction'
    | '/user/signup'
    | '/deck/$action/$data'
    | '/view/card/$id'
    | '/view/deck/$id'
  id:
    | '__root__'
    | '/'
    | '/boards'
    | '/library'
    | '/login'
    | '/mydecks'
    | '/privacy-policy'
    | '/profile'
    | '/requestPasswordReset'
    | '/settings'
    | '/deck/$action'
    | '/decks/$faction'
    | '/user/signup'
    | '/deck/$action/$data'
    | '/view/card/$id'
    | '/view/deck/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardsRoute: typeof BoardsRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  MydecksRoute: typeof MydecksRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  RequestPasswordResetRoute: typeof RequestPasswordResetRoute
  SettingsRoute: typeof SettingsRoute
  DeckActionRoute: typeof DeckActionRouteWithChildren
  DecksFactionRoute: typeof DecksFactionRoute
  UserSignupRoute: typeof UserSignupRoute
  ViewCardIdRoute: typeof ViewCardIdRoute
  ViewDeckIdRoute: typeof ViewDeckIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requestPasswordReset': {
      id: '/requestPasswordReset'
      path: '/requestPasswordReset'
      fullPath: '/requestPasswordReset'
      preLoaderRoute: typeof RequestPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mydecks': {
      id: '/mydecks'
      path: '/mydecks'
      fullPath: '/mydecks'
      preLoaderRoute: typeof MydecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/signup': {
      id: '/user/signup'
      path: '/user/signup'
      fullPath: '/user/signup'
      preLoaderRoute: typeof UserSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$faction': {
      id: '/decks/$faction'
      path: '/decks/$faction'
      fullPath: '/decks/$faction'
      preLoaderRoute: typeof DecksFactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$action': {
      id: '/deck/$action'
      path: '/deck/$action'
      fullPath: '/deck/$action'
      preLoaderRoute: typeof DeckActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/deck/$id': {
      id: '/view/deck/$id'
      path: '/view/deck/$id'
      fullPath: '/view/deck/$id'
      preLoaderRoute: typeof ViewDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/card/$id': {
      id: '/view/card/$id'
      path: '/view/card/$id'
      fullPath: '/view/card/$id'
      preLoaderRoute: typeof ViewCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$action/$data': {
      id: '/deck/$action/$data'
      path: '/$data'
      fullPath: '/deck/$action/$data'
      preLoaderRoute: typeof DeckActionDataRouteImport
      parentRoute: typeof DeckActionRoute
    }
  }
}

interface DeckActionRouteChildren {
  DeckActionDataRoute: typeof DeckActionDataRoute
}

const DeckActionRouteChildren: DeckActionRouteChildren = {
  DeckActionDataRoute: DeckActionDataRoute,
}

const DeckActionRouteWithChildren = DeckActionRoute._addFileChildren(
  DeckActionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsRoute: BoardsRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  MydecksRoute: MydecksRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  RequestPasswordResetRoute: RequestPasswordResetRoute,
  SettingsRoute: SettingsRoute,
  DeckActionRoute: DeckActionRouteWithChildren,
  DecksFactionRoute: DecksFactionRoute,
  UserSignupRoute: UserSignupRoute,
  ViewCardIdRoute: ViewCardIdRoute,
  ViewDeckIdRoute: ViewDeckIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
