export const cards = {
    "BL1": {
        "id": "BL1",
        "factionId": "u",
        "setId": "BL",
        "name": "Strike the Head",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this immediately after an enemy fighter is slain by a friendly fighter if the target was a **leader** or the target's Health characteristic was equal to or greater than the attacker's.",
        "scoreType": "Surge",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL2": {
        "id": "BL2",
        "factionId": "u",
        "setId": "BL",
        "name": "Branching Fate",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this immediately after you make an Attack roll that contained 3 or more dice if each result was a different symbol. If you are the **underdog**, the Attack roll can contain 2 or more dice instead.",
        "scoreType": "Surge",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL3": {
        "id": "BL3",
        "factionId": "u",
        "setId": "BL",
        "name": "Perfect Strike",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this immediately after you make an Attack roll if all of the results were successes.",
        "scoreType": "Surge",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL4": {
        "id": "BL4",
        "factionId": "u",
        "setId": "BL",
        "name": "Critical Effort",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this immediately after you make an Attack roll if any of the results was a :atCrit:.",
        "scoreType": "Surge",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL5": {
        "id": "BL5",
        "factionId": "u",
        "setId": "BL",
        "name": "Get Stuck In",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this immediately after a friendly fighter's Attack if the target was in enemy territory.",
        "scoreType": "Surge",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL6": {
        "id": "BL6",
        "factionId": "u",
        "setId": "BL",
        "name": "Strong Start",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this immediately after an enemy fighter is slain if that fighter was the first fighter slain this combat phase.",
        "scoreType": "Surge",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL7": {
        "id": "BL7",
        "factionId": "u",
        "setId": "BL",
        "name": "Keep Choppin'",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this in an end phase if your warband Attacked 3 or more times this combat phase.",
        "scoreType": "End",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL8": {
        "id": "BL8",
        "factionId": "u",
        "setId": "BL",
        "name": "Fields of Blood",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this in an end phase if 4 or more fighters are damaged and/or slain.",
        "scoreType": "End",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL9": {
        "id": "BL9",
        "factionId": "u",
        "setId": "BL",
        "name": "Go All Out",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this in an end phase if 5 or more fighters have Move and/or Charge tokens.",
        "scoreType": "End",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL10": {
        "id": "BL10",
        "factionId": "u",
        "setId": "BL",
        "name": "On the Edge",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this in an end phase if any enemy fighters are vulnerable.",
        "scoreType": "End",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL11": {
        "id": "BL11",
        "factionId": "u",
        "setId": "BL",
        "name": "Denial",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this in an end phase if there are no enemy fighters in friendly territory.",
        "scoreType": "End",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL12": {
        "id": "BL12",
        "factionId": "u",
        "setId": "BL",
        "name": "Annihilation",
        "type": "Objective",
        "glory": 5,
        "rule": "Score this in an end phase if each enemy fighter is slain.",
        "scoreType": "End",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL13": {
        "id": "BL13",
        "factionId": "u",
        "setId": "BL",
        "name": "Determined Effort",
        "type": "Ploy",
        "glory": null,
        "rule": "Play this immediately after you pick a weapon as part of an Attack. That weapon has +1 Attack dice for that Attack. If you are the **underdog**, that weapon has +2 Attack dice for that Attack instead.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL14": {
        "id": "BL14",
        "factionId": "u",
        "setId": "BL",
        "name": "Twist the Knife",
        "type": "Ploy",
        "glory": null,
        "rule": "Play this immediately after you pick a melee weapon as part of an Attack. That weapon has **Grievous** for that Attack.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL15": {
        "id": "BL15",
        "factionId": "u",
        "setId": "BL",
        "name": "Lure of Battle",
        "type": "Ploy",
        "glory": null,
        "rule": "Pick 1 friendly fighter that is within 2 hexes of another fighter. Push the other fighter 1 hex closer to that friendly fighter.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL16": {
        "id": "BL16",
        "factionId": "u",
        "setId": "BL",
        "name": "Sidestep",
        "type": "Ploy",
        "glory": null,
        "rule": "Pick a friendly fighter. Push that fighter 1 hex.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false,
        "duplicates": [
            "BL16",
            "ES14",
            "PL13"
        ]
    },
    "BL17": {
        "id": "BL17",
        "factionId": "u",
        "setId": "BL",
        "name": "Commanding Stride",
        "type": "Ploy",
        "glory": null,
        "rule": "Push your **leader** up to 3 hexes. That push must end in a starting hex.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false,
        "duplicates": [
            "BL17",
            "PL15"
        ]
    },
    "BL18": {
        "id": "BL18",
        "factionId": "u",
        "setId": "BL",
        "name": "Illusory Fighter",
        "type": "Ploy",
        "glory": null,
        "rule": "Pick a friendly fighter. Remove that fighter from the battlefield, and then place that fighter in an empty starting hex in friendly territory.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL19": {
        "id": "BL19",
        "factionId": "u",
        "setId": "BL",
        "name": "Wings of War",
        "type": "Ploy",
        "glory": null,
        "rule": "Play this immediately after you pick a fighter to Move. That fighter has +2 Move for that Move.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL20": {
        "id": "BL20",
        "factionId": "u",
        "setId": "BL",
        "name": "Shields Up!",
        "type": "Ploy",
        "glory": null,
        "rule": "Pick a friendly fighter. Give that fighter a Guard token.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL21": {
        "id": "BL21",
        "factionId": "u",
        "setId": "BL",
        "name": "Scream of Anger",
        "type": "Ploy",
        "glory": null,
        "rule": "Pick a friendly fighter. Inflict 2 damage on that fighter and then remove 1 of that fighter's Move or Charge tokens.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL22": {
        "id": "BL22",
        "factionId": "u",
        "setId": "BL",
        "name": "Healing Potion",
        "type": "Ploy",
        "glory": null,
        "rule": "Pick a friendly fighter. Heal that fighter. If you are the **underdog**, you can roll a Save dice. On a :dfBlock: or :dfCrit:, heal that fighter again.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false,
        "duplicates": [
            "BL22",
            "ES17"
        ]
    },
    "BL23": {
        "id": "BL23",
        "factionId": "u",
        "setId": "BL",
        "name": "Brawler",
        "type": "Upgrade",
        "glory": 1,
        "rule": "This fighter cannot be Flanked or Surrounded.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL24": {
        "id": "BL24",
        "factionId": "u",
        "setId": "BL",
        "name": "Hidden Aid",
        "type": "Upgrade",
        "glory": 1,
        "rule": "Enemy fighters adjacent to this fighter are Flanked.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL25": {
        "id": "BL25",
        "factionId": "u",
        "setId": "BL",
        "name": "Accurate",
        "type": "Upgrade",
        "glory": 1,
        "rule": "**Strike True:** After you make an Attack roll for this fighter, you can immediately re-roll 1 Attack dice in that Attack roll.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL26": {
        "id": "BL26",
        "factionId": "u",
        "setId": "BL",
        "name": "Great Strength",
        "type": "Upgrade",
        "glory": 2,
        "rule": "This fighter's melee weapons have **Grievous**.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false,
        "duplicates": [
            "BL26",
            "ES32"
        ]
    },
    "BL27": {
        "id": "BL27",
        "factionId": "u",
        "setId": "BL",
        "name": "Deadly Aim",
        "type": "Upgrade",
        "glory": 1,
        "rule": "This fighter's weapons have **Ensnare**.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL28": {
        "id": "BL28",
        "factionId": "u",
        "setId": "BL",
        "name": "Sharpened Points",
        "type": "Upgrade",
        "glory": 1,
        "rule": "This fighter's weapons have **Cleave**.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL29": {
        "id": "BL29",
        "factionId": "u",
        "setId": "BL",
        "name": "Duellist",
        "type": "Upgrade",
        "glory": 1,
        "rule": "**Footwork:** Immediately after this fighter has Attacked, you can push this fighter 1 hex.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false,
        "duplicates": [
            "BL29",
            "ES29"
        ]
    },
    "BL30": {
        "id": "BL30",
        "factionId": "u",
        "setId": "BL",
        "name": "Tough",
        "type": "Upgrade",
        "glory": 2,
        "rule": "No more than 3 damage can be inflicted on this fighter in the same turn.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "BL31": {
        "id": "BL31",
        "factionId": "u",
        "setId": "BL",
        "name": "Great Fortitude",
        "type": "Upgrade",
        "glory": 2,
        "rule": "This fighter has +1 Health.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false,
        "duplicates": [
            "BL31",
            "ES30",
            "CC30"
        ]
    },
    "BL32": {
        "id": "BL32",
        "factionId": "u",
        "setId": "BL",
        "name": "Keen Eye",
        "type": "Upgrade",
        "glory": 2,
        "rule": "This fighter's melee weapons have +1 Attack dice.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false,
        "duplicates": [
            "BL32",
            "ES31"
        ]
    },
    "ES1": {
        "id": "ES1",
        "factionId": "u",
        "setId": "ES",
        "name": "Sally Forth",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this immediately after your opponent's Action step if a friendly fighter with any Charge tokens hold a treasure token in enemy territory.",
        "scoreType": "Surge",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES2": {
        "id": "ES2",
        "factionId": "u",
        "setId": "ES",
        "name": "Stand Firm",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this immediately after your opponent's Action step if a friendly fighter with any Stagger tokens holds a treasure token in enemy territory.",
        "scoreType": "Surge",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES3": {
        "id": "ES3",
        "factionId": "u",
        "setId": "ES",
        "name": "Step by Step",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this immediately after your opponent's Action step if a friendly fighter with any Move tokens holds a treasure token in enemy territory. If you are the **underdog**, that friendly fighter can have any Charge tokens instead.",
        "scoreType": "Surge",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES4": {
        "id": "ES4",
        "factionId": "u",
        "setId": "ES",
        "name": "Unassailable",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this immediately after an enemy fighter's Attack if a friendly fighter holding a treasure token was the target of that Attack.",
        "scoreType": "Surge",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES5": {
        "id": "ES5",
        "factionId": "u",
        "setId": "ES",
        "name": "Aggressive Defender",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this immediately after a friendly fighter's Attack if the attacker is holding a treasure token.",
        "scoreType": "Surge",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES6": {
        "id": "ES6",
        "factionId": "u",
        "setId": "ES",
        "name": "Careful Advance",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this immediately after a friendly fighter Moves if 2 or more friendly fighters that have Move tokens are in enemy territory.",
        "scoreType": "Surge",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES7": {
        "id": "ES7",
        "factionId": "u",
        "setId": "ES",
        "name": "Hold Treasure Token 1 or 2",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this in an end phase if a friendly fighter holds treasure token 1 or 2.",
        "scoreType": "End",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES8": {
        "id": "ES8",
        "factionId": "u",
        "setId": "ES",
        "name": "Hold Treasure Token 3 or 4",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this in an end phase if a friendly fighter holds treasure token 3 or 4.",
        "scoreType": "End",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES9": {
        "id": "ES9",
        "factionId": "u",
        "setId": "ES",
        "name": "Hold Treasure Token 5",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this in an end phase if a friendly fighter holds treasure token 5.",
        "scoreType": "End",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES10": {
        "id": "ES10",
        "factionId": "u",
        "setId": "ES",
        "name": "Slow Advance",
        "type": "Objective",
        "glory": 2,
        "rule": "Score this in an end phase if your warband holds any treasure tokens in both neutral territory and enemy territory.",
        "scoreType": "End",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES11": {
        "id": "ES11",
        "factionId": "u",
        "setId": "ES",
        "name": "Iron Grasp",
        "type": "Objective",
        "glory": 2,
        "rule": "Score this in an end phase if your warband holds all of the treasure tokens in a friendly and/or enemy territory.",
        "scoreType": "End",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES12": {
        "id": "ES12",
        "factionId": "u",
        "setId": "ES",
        "name": "Supremacy",
        "type": "Objective",
        "glory": 3,
        "rule": "Score this in an end phase if 2 or more friendly fighters with a total Bounty characteristic of 3 or more hold treasure tokens.",
        "scoreType": "End",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES13": {
        "id": "ES13",
        "factionId": "u",
        "setId": "ES",
        "name": "Switch Things Up",
        "type": "Ploy",
        "glory": null,
        "rule": "Pick 2 treasure tokens. Swap the positions of those treasure tokens.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES14": {
        "id": "ES14",
        "factionId": "u",
        "setId": "ES",
        "name": "Sidestep",
        "type": "Ploy",
        "glory": null,
        "rule": "Pick a friendly fighter. Push that fighter 1 hex.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false,
        "duplicates": [
            "BL16",
            "ES14",
            "PL13"
        ]
    },
    "ES15": {
        "id": "ES15",
        "factionId": "u",
        "setId": "ES",
        "name": "The Extra Mile",
        "type": "Ploy",
        "glory": null,
        "rule": "Play this immediately after a friendly fighter Moves. Push that fighter 1 hex. That push must end on a feature token.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES16": {
        "id": "ES16",
        "factionId": "u",
        "setId": "ES",
        "name": "Settle In",
        "type": "Ploy",
        "glory": null,
        "rule": "Pick a friendly fighter on a feature token. Give that fighter a Guard token.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES17": {
        "id": "ES17",
        "factionId": "u",
        "setId": "ES",
        "name": "Healing Potion",
        "type": "Ploy",
        "glory": null,
        "rule": "Pick a friendly fighter. Heal that fighter. If you are the **underdog**, you can roll a Save dice. On a :dfBlock: or :dfCrit:, heal that fighter again.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false,
        "duplicates": [
            "BL22",
            "ES17"
        ]
    },
    "ES18": {
        "id": "ES18",
        "factionId": "u",
        "setId": "ES",
        "name": "Hidden Paths",
        "type": "Ploy",
        "glory": null,
        "rule": "Pick a friendly fighter in an edge hex. Remove that fighter from the battlefield, and then place that fighter in a different empty edge hex. Then, give that fighter a Move token, unless you are the **underdog**.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES19": {
        "id": "ES19",
        "factionId": "u",
        "setId": "ES",
        "name": "Confusion",
        "type": "Ploy",
        "glory": null,
        "rule": "Pick 2 adjacent fighters. Remove those fighters from the battlefield and then place each in the hex the other was removed from.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES20": {
        "id": "ES20",
        "factionId": "u",
        "setId": "ES",
        "name": "Hold the Line!",
        "type": "Ploy",
        "glory": null,
        "rule": "Fighters cannot be driven back. This effect persists until the end of the next Action step.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES21": {
        "id": "ES21",
        "factionId": "u",
        "setId": "ES",
        "name": "Shoulder Throw",
        "type": "Ploy",
        "glory": null,
        "rule": "Play this immediately after a friendly fighter's successful Attack if the target is adjacent. Remove the target from the battlefield, and then place them in a different empty hex adjacent to the attacker.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES22": {
        "id": "ES22",
        "factionId": "u",
        "setId": "ES",
        "name": "By the Numbers",
        "type": "Ploy",
        "glory": null,
        "rule": "Draw a number of Power cards equal to the number of treasure tokens held by your warband.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES23": {
        "id": "ES23",
        "factionId": "u",
        "setId": "ES",
        "name": "Stubborn to the End",
        "type": "Upgrade",
        "glory": 1,
        "rule": "If this fighter is the target of an Attack, the attacker cannot use Overrun.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES24": {
        "id": "ES24",
        "factionId": "u",
        "setId": "ES",
        "name": "Inviolate",
        "type": "Upgrade",
        "glory": 1,
        "rule": "This fighter cannot be Flanked or Surrounded while they hold a treasure token.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES25": {
        "id": "ES25",
        "factionId": "u",
        "setId": "ES",
        "name": "Great Speed",
        "type": "Upgrade",
        "glory": null,
        "rule": "This fighter has +1 Move.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false,
        "duplicates": [
            "ES25",
            "PL23"
        ]
    },
    "ES26": {
        "id": "ES26",
        "factionId": "u",
        "setId": "ES",
        "name": "Share Reflexes",
        "type": "Upgrade",
        "glory": 2,
        "rule": "This fighter has +1 Save, to a maximum of 2.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES27": {
        "id": "ES27",
        "factionId": "u",
        "setId": "ES",
        "name": "Brute Momentum",
        "type": "Upgrade",
        "glory": 1,
        "rule": "This fighter cannot be driven back while they have any Charge tokens.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES28": {
        "id": "ES28",
        "factionId": "u",
        "setId": "ES",
        "name": "Agile",
        "type": "Upgrade",
        "glory": 2,
        "rule": "**Deft:** After you make a Save roll for this fighter, you can immediately re-roll 1 Save dice in that Save roll.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "ES29": {
        "id": "ES29",
        "factionId": "u",
        "setId": "ES",
        "name": "Duellist",
        "type": "Upgrade",
        "glory": 1,
        "rule": "**Footwork:** Immediately after this fighter has Attacked, you can push this fighter 1 hex.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false,
        "duplicates": [
            "BL29",
            "ES29"
        ]
    },
    "ES30": {
        "id": "ES30",
        "factionId": "u",
        "setId": "ES",
        "name": "Great Fortitude",
        "type": "Upgrade",
        "glory": 2,
        "rule": "This fighter has +1 Health.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false,
        "duplicates": [
            "BL31",
            "ES30",
            "CC30"
        ]
    },
    "ES31": {
        "id": "ES31",
        "factionId": "u",
        "setId": "ES",
        "name": "Keen Eye",
        "type": "Upgrade",
        "glory": 2,
        "rule": "This fighter's melee weapons have +1 Attack dice.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false,
        "duplicates": [
            "BL32",
            "ES31"
        ]
    },
    "ES32": {
        "id": "ES32",
        "factionId": "u",
        "setId": "ES",
        "name": "Great Strength",
        "type": "Upgrade",
        "glory": 2,
        "rule": "This fighter's melee weapons have **Grievous**.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false,
        "duplicates": [
            "BL26",
            "ES32"
        ]
    },
    "PL1": {
        "id": "PL1",
        "factionId": "u",
        "setId": "PL",
        "name": "Broken Prospects",
        "type": "Objective",
        "glory": 2,
        "rule": "Score this in an end phase if 3 or more different treasure tokens were Delved by your warband this battle round or if a treasure token held by an enemy fighter at the start of the battle round was Delved by your warband this battle round.",
        "scoreType": "End",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL2": {
        "id": "PL2",
        "factionId": "u",
        "setId": "PL",
        "name": "Against the Odds",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this in an end phase if an odd-numbered treasure token was Delved by your warband this battle round.",
        "scoreType": "End",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL3": {
        "id": "PL3",
        "factionId": "u",
        "setId": "PL",
        "name": "Lost in the Depths",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this in an end phase if no friendly fighters are adjacent and any friendly fighters are not slain.",
        "scoreType": "End",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL4": {
        "id": "PL4",
        "factionId": "u",
        "setId": "PL",
        "name": "Desolate Homeland",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this in an end phase if there are 1 or fewer treasure tokens in friendly territory.",
        "scoreType": "End",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL5": {
        "id": "PL5",
        "factionId": "u",
        "setId": "PL",
        "name": "Torn Landscape",
        "type": "Objective",
        "glory": 2,
        "rule": "Score this in an end phase if there are 2 or fewer treasure tokens on the battlefield.",
        "scoreType": "End",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL6": {
        "id": "PL6",
        "factionId": "u",
        "setId": "PL",
        "name": "Strip the Realm",
        "type": "Objective",
        "glory": 3,
        "rule": "Score this in an end phase if there are no treasure tokens on the battlefield or if no enemy fighters hold any treasure tokens.",
        "scoreType": "End",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL7": {
        "id": "PL7",
        "factionId": "u",
        "setId": "PL",
        "name": "Aggressive Claimant",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this immediately after a friendly fighter's successful Attack if the target was in neutral territory, or the target was holding a treasure token when you picked them to be the target of that Attack and is no longer holding that treasure token.",
        "scoreType": "Surge",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL8": {
        "id": "PL8",
        "factionId": "u",
        "setId": "PL",
        "name": "Claim the Prize",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this immediately after a friendly fighter Delves in enemy territory. If you are the **underdog**, that Delve can be in friendly territory instead.",
        "scoreType": "Surge",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL9": {
        "id": "PL9",
        "factionId": "u",
        "setId": "PL",
        "name": "Delving for Wealth",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this immediately after your warband Delves for the third or subsequent time this combat phase.",
        "scoreType": "Surge",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL10": {
        "id": "PL10",
        "factionId": "u",
        "setId": "PL",
        "name": "Share the Load",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this immediately after a friendly fighter Moves, if that fighter and any other friendly fighters are each on feature tokens.",
        "scoreType": "Surge",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL11": {
        "id": "PL11",
        "factionId": "u",
        "setId": "PL",
        "name": "Hostile Takeover",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this immediately after the second or subsequent Attack made by your warband that was not part of a Charge.",
        "scoreType": "Surge",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL12": {
        "id": "PL12",
        "factionId": "u",
        "setId": "PL",
        "name": "Careful Survey",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this immediately after an Action step if there is a friendly fighter in each territory.",
        "scoreType": "Surge",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL13": {
        "id": "PL13",
        "factionId": "u",
        "setId": "PL",
        "name": "Sidestep",
        "type": "Ploy",
        "glory": null,
        "rule": "Pick a friendly fighter. Push that fighter 1 hex.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false,
        "duplicates": [
            "BL16",
            "ES14",
            "PL13"
        ]
    },
    "PL14": {
        "id": "PL14",
        "factionId": "u",
        "setId": "PL",
        "name": "Prideful Duellist",
        "type": "Ploy",
        "glory": null,
        "rule": "Play this immediately after a friendly fighter's Attack if the attacker is in enemy territory. Heal the attacker.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL15": {
        "id": "PL15",
        "factionId": "u",
        "setId": "PL",
        "name": "Commanding Stride",
        "type": "Ploy",
        "glory": null,
        "rule": "Push your **leader** up to 3 hexes. That push must end in a starting hex.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false,
        "duplicates": [
            "BL17",
            "PL15"
        ]
    },
    "PL16": {
        "id": "PL16",
        "factionId": "u",
        "setId": "PL",
        "name": "Crumbling Mine",
        "type": "Ploy",
        "glory": null,
        "rule": "Pick a treasure token that is not held. Flip that treasure token.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL17": {
        "id": "PL17",
        "factionId": "u",
        "setId": "PL",
        "name": "Explosive Charges",
        "type": "Ploy",
        "glory": null,
        "rule": "**Domain:** Friendly fighters have +1 Move while using Charge abilities. This effect persists until the end of the battle round or until another Domain card is played.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL18": {
        "id": "PL18",
        "factionId": "u",
        "setId": "PL",
        "name": "Wary Delver",
        "type": "Ploy",
        "glory": null,
        "rule": "Pick a friendly fighter with any Charge tokens. Give that fighter a Guard token.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL19": {
        "id": "PL19",
        "factionId": "u",
        "setId": "PL",
        "name": "Brash Scout",
        "type": "Ploy",
        "glory": null,
        "rule": "Play this immediately after you make an Attack roll for a fighter in enemy territory. Re-roll 1 dice in that Attack roll. If you are the **underdog**, you can re-roll each dice in that Attack roll instead.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL20": {
        "id": "PL20",
        "factionId": "u",
        "setId": "PL",
        "name": "Sudden Blast",
        "type": "Ploy",
        "glory": null,
        "rule": "Pick an enemy fighter adjacent to a friendly fighter. Give that enemy fighter a Stagger token.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL21": {
        "id": "PL21",
        "factionId": "u",
        "setId": "PL",
        "name": "Tunnelling Terror",
        "type": "Ploy",
        "glory": null,
        "rule": "Pick a friendly fighter with no Move or Charge tokens. Remove that fighter from the battlefield, and then place that fighter in an empty stagger hex. Then, give that fighter a Charge token. If you are the **underdog**, you can give that fighter a Move token instead.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL22": {
        "id": "PL22",
        "factionId": "u",
        "setId": "PL",
        "name": "Trapped Cache",
        "type": "Ploy",
        "glory": null,
        "rule": "Pick an undamaged enemy fighter within 1 hex of a treasure token. Inflict 1 damage on that fighter.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL23": {
        "id": "PL23",
        "factionId": "u",
        "setId": "PL",
        "name": "Great Speed",
        "type": "Upgrade",
        "glory": null,
        "rule": "This fighter have +1 Move.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false,
        "duplicates": [
            "ES25",
            "PL23"
        ]
    },
    "PL24": {
        "id": "PL24",
        "factionId": "u",
        "setId": "PL",
        "name": "Swift Step",
        "type": "Upgrade",
        "glory": 1,
        "rule": "**Quick:** Immediately after this fighter has Charged, you can push this fighter 1 hex.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL25": {
        "id": "PL25",
        "factionId": "u",
        "setId": "PL",
        "name": "Burrowing Strike",
        "type": "Upgrade",
        "glory": 1,
        "rule": "**Melee Attack action** \\n [:Hex: 2 - :atFury: 2 - :boom: 2] \\n This weapon has +1 Attack dice while this fighter has any Stagger tokens or is on a feature token.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL26": {
        "id": "PL26",
        "factionId": "u",
        "setId": "PL",
        "name": "Tough Enough",
        "type": "Upgrade",
        "glory": 1,
        "rule": "While this fighter is in enemy territory, Save rolls for this fighter cannot be affected by **Cleave** and **Ensnare**.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL27": {
        "id": "PL27",
        "factionId": "u",
        "setId": "PL",
        "name": "Canny Sapper",
        "type": "Upgrade",
        "glory": null,
        "rule": "**Sneaky:** Immediately after you play a Ploy in a Power step, you can remove this fighter from the battlefield. Place this fighter in an empty stagger hex or in an empty starting hex in friendly territory, and then discard this card.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL28": {
        "id": "PL28",
        "factionId": "u",
        "setId": "PL",
        "name": "Impossibly Quick",
        "type": "Upgrade",
        "glory": 1,
        "rule": "This fighter has +1 Save. \\n Immediately discard this Upgrade after an enemy fighter's failed Attack if this fighter was the target.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL29": {
        "id": "PL29",
        "factionId": "u",
        "setId": "PL",
        "name": "Linebreaker",
        "type": "Upgrade",
        "glory": 1,
        "rule": "This fighter's weapons have **Brutal**.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL30": {
        "id": "PL30",
        "factionId": "u",
        "setId": "PL",
        "name": "Excavating Blast",
        "type": "Upgrade",
        "glory": 1,
        "rule": "**Ranged Attack action** \\n [:Hex: 3 - :atSmash: 2 - :boom: 1] \\n This weapon has **Stagger** while this fighter is in enemy territory.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL31": {
        "id": "PL31",
        "factionId": "u",
        "setId": "PL",
        "name": "Gloryseeker",
        "type": "Upgrade",
        "glory": 1,
        "rule": "This fighter's melee weapons have **Grievous** if the target has a Health characteristic of 4 or more.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "PL32": {
        "id": "PL32",
        "factionId": "u",
        "setId": "PL",
        "name": "Frenzy of Greed",
        "type": "Upgrade",
        "glory": 2,
        "rule": "While this fighter is on a treasure token in enemy territory or is in a stagger hex, Save rolls for this fighter are not affected by **Cleave** and **Ensnare** and this fighter cannot be given Stagger tokens.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC1": {
        "id": "CC1",
        "factionId": "u",
        "setId": "CC",
        "name": "Spread Havoc",
        "type": "Objective",
        "glory": null,
        "rule": "Score this in an end phase. Gain a number of Glory points equal to your Cataclysm value, to a maximum of 2.",
        "scoreType": "End",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC2": {
        "id": "CC2",
        "factionId": "u",
        "setId": "CC",
        "name": "Hounds of War",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this in an end phase if 2 or more enemy fighters are slain and/or damaged and any of those fighters were slain in the preceding combat phase.",
        "scoreType": "End",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC3": {
        "id": "CC3",
        "factionId": "u",
        "setId": "CC",
        "name": "Set Explosives",
        "type": "Objective",
        "glory": 2,
        "rule": "Score this in an end phase if your warband holds 2 or more treasure tokens and holds all of the treasure tokens in any territories.",
        "scoreType": "End",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC4": {
        "id": "CC4",
        "factionId": "u",
        "setId": "CC",
        "name": "Wreckers",
        "type": "Objective",
        "glory": 2,
        "rule": "Score this in an end phase if the number of damaged and/or slain enemy fighters is greater than your Cataclysm value.",
        "scoreType": "End",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC5": {
        "id": "CC5",
        "factionId": "u",
        "setId": "CC",
        "name": "Uneven Contest",
        "type": "Objective",
        "glory": 2,
        "rule": "Score this in an end phase if your warband holds each odd-numbered treasure token.",
        "scoreType": "End",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC6": {
        "id": "CC6",
        "factionId": "u",
        "setId": "CC",
        "name": "Loaded for Bear",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this in an end phase if any friendly fighters are each equipped with 3 or more Upgrades.",
        "scoreType": "End",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC7": {
        "id": "CC7",
        "factionId": "u",
        "setId": "CC",
        "name": "Collateral Damage",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this immediately after you advance your Cataclysm tracker 1 step as a result of a friendly fighter being slain. If you are the **underdog**, score this after you advance your Cataclysm tracker 1 step for any reason instead.",
        "scoreType": "Surge",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC8": {
        "id": "CC8",
        "factionId": "u",
        "setId": "CC",
        "name": "Too Close for Comfort",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this immediately after your opponent's Power step if each friendly fighter is within 2 hexes of any enemy fighters.",
        "scoreType": "Surge",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC9": {
        "id": "CC9",
        "factionId": "u",
        "setId": "CC",
        "name": "Shocking Assault",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this immediately after your opponent's Action step if your warband holds all of the treasure tokens in neutral territory.",
        "scoreType": "Surge",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC10": {
        "id": "CC10",
        "factionId": "u",
        "setId": "CC",
        "name": "Nowhere to Run",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this immediately after an Action step if all friendly fighters have Move and/or Charge tokens and there is a friendly fighter in each territory.",
        "scoreType": "Surge",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC11": {
        "id": "CC11",
        "factionId": "u",
        "setId": "CC",
        "name": "The Perfect Cut",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this immediately after a friendly fighter's successful melee Attack if no result in the target's Save roll was a success.",
        "scoreType": "Surge",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC12": {
        "id": "CC12",
        "factionId": "u",
        "setId": "CC",
        "name": "Overwhelming Force",
        "type": "Objective",
        "glory": 1,
        "rule": "Score this immediately after a friendly fighter's successful melee Attack if the Attack roll contained 4 or more dice.",
        "scoreType": "Surge",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC13": {
        "id": "CC13",
        "factionId": "u",
        "setId": "CC",
        "name": "Savage Blow",
        "type": "Ploy",
        "glory": null,
        "rule": "Play this immediately after you pick a weapon as part of an Attack. Rolls of :atSup2: count as successes for that Attack.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC14": {
        "id": "CC14",
        "factionId": "u",
        "setId": "CC",
        "name": "The End is Nigh",
        "type": "Ploy",
        "glory": null,
        "rule": "**Domain:** After each Action step, the player whose turn it is rolls a number of Attack dice equal to their Cataclysm value, or 1 Attack dice if they have no such value. \\n If the roll contains any :atFury: or :atCrit:, their opponent must discard a Power card. This effect persists until the end of the battle round, until another Domain card is played, or until you advance your Cataclysm tracker.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC15": {
        "id": "CC15",
        "factionId": "u",
        "setId": "CC",
        "name": "Growing Concerns",
        "type": "Ploy",
        "glory": null,
        "rule": "Enemy fighters have -X Move in the next Action step, where X is your Cataclysm value.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC16": {
        "id": "CC16",
        "factionId": "u",
        "setId": "CC",
        "name": "Total Collapse",
        "type": "Ploy",
        "glory": null,
        "rule": "Roll a number of Attack dice equal to your Cataclysm value. If the roll contains :atFury: or :atCrit:, pick a fighter. \\n Inflict 1 damage on that fighter. If you picked a friendly fighter, you can inflict damage on that fighter up to your Cataclysm value instead.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC17": {
        "id": "CC17",
        "factionId": "u",
        "setId": "CC",
        "name": "Violent Blast",
        "type": "Ploy",
        "glory": null,
        "rule": "Pick a stagger hex. Push each fighter within 1 hex of that stagger hex 1 hex.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC18": {
        "id": "CC18",
        "factionId": "u",
        "setId": "CC",
        "name": "Sunder the Realm",
        "type": "Ploy",
        "glory": null,
        "rule": "Roll a number of Attack dice equal to your Cataclysm value for each fighter within 1 hex of neutral territory. \\n If the roll contains any :atSmash: or :atCrit:, inflict 1 damage on that fighter.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC19": {
        "id": "CC19",
        "factionId": "u",
        "setId": "CC",
        "name": "Raging Tremors",
        "type": "Ploy",
        "glory": null,
        "rule": "Pick a number of enemy fighters up to your Cataclysm value. Give each of those fighters a Stagger token.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC20": {
        "id": "CC20",
        "factionId": "u",
        "setId": "CC",
        "name": "Counter-charge",
        "type": "Ploy",
        "glory": null,
        "rule": "Play this immediately after a friendly fighter is picked to be the target of an Attack. Pick another friendly fighter. Push that fighter up to 3 hexes. That push must end adjacent to the attacker.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC21": {
        "id": "CC21",
        "factionId": "u",
        "setId": "CC",
        "name": "Do or Die",
        "type": "Ploy",
        "glory": null,
        "rule": "Pick a friendly fighter. Inspire that fighter. This effect persists for X Action steps where X is your Cataclysm value. After that effect ends, do not discard this card. Instead, Uninspire that fighter. That fighter cannot be Inspired again. This effect persists until the end of the game.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC22": {
        "id": "CC22",
        "factionId": "u",
        "setId": "CC",
        "name": "Improvised Attack",
        "type": "Ploy",
        "glory": null,
        "rule": "Pick a friendly fighter. That fighter immediately Attacks with the following weapon, where X is your Cataclysm value. \\n **Ranged Attack action** \\n [:Hex: 3 - :atSmash: X - :boom: 1] \\n This weapon cannot be modified.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC23": {
        "id": "CC23",
        "factionId": "u",
        "setId": "CC",
        "name": "Bringer of Doom",
        "type": "Upgrade",
        "glory": 1,
        "rule": "**Tick Tock:** After this card is discarded during a Combat Phase, you can immediately advance your Cataclysm tracker 1 step.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC24": {
        "id": "CC24",
        "factionId": "u",
        "setId": "CC",
        "name": "Visions of Ruin",
        "type": "Upgrade",
        "glory": 1,
        "rule": "This fighter has +X Move, where X is your cataclysm value. \\n Immediately after this fighter Moves, give this fighter a Stagger token.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC25": {
        "id": "CC25",
        "factionId": "u",
        "setId": "CC",
        "name": "Extinction's Edge",
        "type": "Upgrade",
        "glory": 1,
        "rule": "**Ever Closer:** Immediately advance your Cataclysm tracker 1 step after an enemy fighter is slain by this fighter. Then, if your Cataclysm value is 2 or greater, discard this card.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC26": {
        "id": "CC26",
        "factionId": "u",
        "setId": "CC",
        "name": "Driven by Pain",
        "type": "Upgrade",
        "glory": 1,
        "rule": "**Insensate:** Immediately after this fighter is driven back, you can heal this fighter.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC27": {
        "id": "CC27",
        "factionId": "u",
        "setId": "CC",
        "name": "Inescapable Grasp",
        "type": "Upgrade",
        "glory": 1,
        "rule": "This fighter's melee weapons have **Ensnare**.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC28": {
        "id": "CC28",
        "factionId": "u",
        "setId": "CC",
        "name": "Utter Conviction",
        "type": "Upgrade",
        "glory": 1,
        "rule": "This fighter's Save characteristic is X, where X is your Cataclysm value, and cannot be modified further.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC29": {
        "id": "CC29",
        "factionId": "u",
        "setId": "CC",
        "name": "Burnt Out",
        "type": "Upgrade",
        "glory": 1,
        "rule": "**Smoulder:** Pick a friendly fighter. Give that fighter a Stagger token. Then, draw 2 Power cards. If you are the **underdog**, draw 3 Power cards instead.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC30": {
        "id": "CC30",
        "factionId": "u",
        "setId": "CC",
        "name": "Great Fortitude",
        "type": "Upgrade",
        "glory": 2,
        "rule": "This fighter has +1 Health.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false,
        "duplicates": [
            "BL31",
            "ES30",
            "CC30"
        ]
    },
    "CC31": {
        "id": "CC31",
        "factionId": "u",
        "setId": "CC",
        "name": "Hurled Weapon",
        "type": "Upgrade",
        "glory": 1,
        "rule": "**Ranged Attack action** \\n [:Hex: 3 - :atSmash: 2 - :boom: 1 -(:atCrit: **Cleave**)-]",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    },
    "CC32": {
        "id": "CC32",
        "factionId": "u",
        "setId": "CC",
        "name": "Desperate Rage",
        "type": "Upgrade",
        "glory": 1,
        "rule": "**Melee Attack action** \\n [:Hex: 1 - :atSmash: 2 - :boom: 3] \\n Immediately after this fighter has Attacked with this weapon, inflict 1 damage on this fighter.",
        "scoreType": "-",
        "status": "V--_V-_V",
        "rotated": false
    }
} as const;